# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

#  List xcodes simulators and runtimes with:
#  xcrun simctl list

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  execute-unit-tests:
    name: Unit Tests
    runs-on: macos-14
    strategy:
      matrix:
        config: [debug]
        platform: [macOS]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Select Xcode 15.2
      run: sudo xcode-select -s /Applications/Xcode_15.2.app

    - name: Run tests
      run: TEMP_DIR=${{ runner.temp }} PLATFORM=${{ matrix.platform }} CONFIG=${{ matrix.config }} make test

    - name: Prepare Code Coverage
      run: make coverage-export

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.lcov
        flags: unittests
