name: Documentation

on:
  release:
    types:
      - published
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-documentation:
    name: Build documentation
    runs-on: macos-14
    steps:
      - name: Select Xcode 15.2
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Checkout Package
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout github-pages Branch
        uses: actions/checkout@v4
        with:
          ref: github-pages
          path: docs

      - name: Build documentation
        run: >
          rm -rf docs/.git;
          rm -rf docs/main;
          git tag -l --sort=-v:refname | grep -e "\d\+\.\d\+.0" | tail -n +6 | xargs -I {} rm -rf {};

          for tag in $(echo "main"; git tag -l --sort=-v:refname | grep -e "\d\+\.\d\+.0" | head -6);
          do
            if [ -d "docs/$tag/data/documentation/swift-foundation-extras" ] 
            then 
              echo "✅ Documentation for "$tag" already exists.";
            else 
              echo "⏳ Generating documentation for SwiftFoundationExtras @ "$tag" release.";
              rm -rf "docs/$tag";

              git checkout .;
              git checkout "$tag";

              swift package \
                --allow-writing-to-directory docs/"$tag" \
                generate-documentation \
                --target SwiftFoundationExtras \
                --output-path docs/"$tag" \
                --transform-for-static-hosting \
                --hosting-base-path /swift-foundation-extras/"$tag" \
                && echo "✅ Documentation generated for SwiftFoundationExtras @ "$tag" release." \
                || echo "⚠️ Documentation skipped for SwiftFoundationExtras @ "$tag".";
            fi;
          done

      - name: Fix permissions
        run: 'sudo chown -R $USER docs'

      - name: Publish documentation to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: github-pages
          folder: docs
          single-commit: true